# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: registry.gitlab.com/physmin/physmin-docker

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
 - cd ./functions/
 - npm update --dev

test_async:
  stage: test
  script:
   - npm test

deploy:
  stage: deploy
  when: manual
  script:
  - firebase deploy --token $FIREBASE_TOKEN

#test_db:
#  script:
#   - npm install
#   - node ./specs/start.js ./specs/db-postgres.spec.js
